config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("kanban/", include("kanban.urls")),
    path('kanban/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
]

kanban/urls.py
from django.urls import path

from . import views

app_name = "kanban"




urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path('signup/', views.signup, name='signup'),
    path("users/<int:pk>/", views.UserDetailView.as_view(), name="users_detail"),
    path("users/<int:pk>/update/", views.UserUpdateView.as_view(), name="users_update"),
    path("lists/", views.ListListView.as_view(), name="lists_list"),
    path("lists/create/", views.ListCreateView.as_view(), name="lists_create"), 
    path("lists/<int:pk>/", views.ListDetailView.as_view(), name="lists_detail"),
    path("lists/<int:pk>/update/", views.ListUpdateView.as_view(), name="lists_update"),
    path("lists/<int:pk>/delete/", views.ListDeleteView.as_view(), name="lists_delete"),

]

kanban/models.py
from django.contrib.auth.models import User
from django.db import models

class List(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Card(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    list = models.ForeignKey(List, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

kanban/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import List


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("username", "last_name", "first_name", "email",)
        

class ListForm(forms.ModelForm):

    class Meta:
        model = List
        fields = ("title",)

kanban/views.py
from django.contrib.auth import login 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect , resolve_url 
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, CreateView, ListView, DeleteView

from .forms import UserForm, ListForm
from . models import List
from .mixins import OnlyYouMixin






def index(request):
    return render(request, "kanban/index.html")
    
def home(request):
    return render(request, "kanban/home.html")
    

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user_instance = form.save()
            login(request, user_instance)
            return redirect("kanban:home")
    else:
        form = UserCreationForm()

    context = {
        "form": form
    }
    return render(request, 'kanban/signup.html', context)
    
@login_required # 追加
def home(request):
    return render(request, "kanban/home.html")


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user_instance = form.save()
            login(request, user_instance)
            return redirect("kanban:home")
    else:
        form = UserCreationForm()
        context = {
            "form": form
        }
    return render(request, 'kanban/signup.html', context)
    
    
class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "kanban/users/detail.html"
    
class UserUpdateView(OnlyYouMixin, UpdateView):
    model = User
    template_name = "kanban/users/update.html"
    form_class = UserForm

    def get_success_url(self):
        return resolve_url('kanban:users_detail', pk=self.kwargs['pk'])
        
class ListCreateView(LoginRequiredMixin, CreateView):
    model = List
    template_name = "kanban/lists/create.html"
    form_class = ListForm
    success_url = reverse_lazy("kanban:lists_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        
class ListListView(LoginRequiredMixin, ListView):
    model = List
    template_name = "kanban/lists/list.html"
    
class ListDetailView(LoginRequiredMixin, DetailView):
    model = List
    template_name = "kanban/lists/detail.html"
    
class ListUpdateView(LoginRequiredMixin, UpdateView):
    model = List
    template_name = "kanban/lists/update.html"
    form_class = ListForm

    def get_success_url(self):
        return resolve_url('kanban:lists_detail', pk=self.kwargs['pk'])

class ListDeleteView(LoginRequiredMixin, DeleteView):
    model = List
    template_name = "kanban/lists/delete.html"
    success_url = reverse_lazy("kanban:lists_list")

kanban/templates/kanban/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>kanban</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'kanban:index' %}">kanban</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>
          <ul class="navbar-nav">
             {% if request.user.is_authenticated %}
               <li class="nav-item">
                <a class="nav-link" href="{% url 'kanban:users_detail' request.user.pk %}">{{ request.user.username }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'kanban:lists_list' %}">リスト一覧</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">ログイン</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'kanban:signup' %}">サインアップ</a>
              </li>
              {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

kanban/templates/kanban/home.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ完了</h1>
  <p>サインアップが完了しました。</p>
</div>
{% endblock %}

kanban/templates/kanban/index.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">kanban</h1>
  <p class="lead">kanbanでタスク管理をしてみましょう。</p>
  <hr class="my-4">
  <p>このアプリケーションはDjangoで作られています。</p>
  <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">ログイン</a>
  <a class="btn btn-primary btn-lg" href="{% url 'kanban:signup' %}" role="button">サインアップ</a>
</div>
{% endblock %}

kanban/templates/kanban/lists/create.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト作成</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

kanban/templates/kanban/lists/delete.html
{% extends "kanban/base.html" %}

{% block content %}
<h1>リスト削除</h1>
<form method="post">
  {% csrf_token %}
  <p>リスト "{{ list.title }}" を本当に削除してもよろしいですか？</p>
  <button type="submit" class="btn btn-danger">確認</button>
</form>
{% endblock %}

kanban/templates/kanban/lists/detail.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト詳細</h1>
  <dl class="row">
    <dt class="col-sm-3">タイトル</dt>
    <dd class="col-sm-9">{{ list.title }}</dd>
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ list.user.username }}</dd>
  </dl>
  
  <a class="btn btn-primary" href="{% url 'kanban:lists_update' list.pk  %}" role="button">編集</a>
  <a class="btn btn-danger" href="{% url 'kanban:lists_delete' list.pk  %}" role="button">削除</a>

</div>
{% endblock %}

kanban/templates/kanban/lists/list.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト一覧</h1>
  <a class="btn btn-primary my-3" href="{% url 'kanban:lists_create' %}" role="button">作成</a> <!-- 追加 -->
  <div class="card-columns">
    {% for list in list_list %}
    <a href="{% url 'kanban:lists_detail' list.pk %}" class="card"> <!-- aタグに変更 -->
      <div class="card-body">
        <h5 class="card-title">{{ list.title }}</h5>
        <footer>
          <small class="text-muted">作成者: {{ list.user.username }}</small>
        </footer>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

kanban/templates/kanban/lists/lists.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト一覧</h1>
  <div class="card-columns">
    {% for list in list_list %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ list.title }}</h5>
        <footer>
          <small class="text-muted">作成者: {{ list.user.username }}</small>
        </footer>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

kanban/templates/kanban/lists/update.html
{% extends "kanban/base.html" %}

{% block content %}
<h1>リスト編集</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">送信</button>
</form>
{% endblock %}

kanban/templates/kanban/signup.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">登録</button>
  </form>
</div>
{% endblock %}

kanban/templates/kanban/users/detail.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>ユーザー詳細</h1>
    <dl class="row">
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ user.username }}</dd>
    <dt class="col-sm-3">姓</dt>
    <dd class="col-sm-9">{{ user.last_name }}</dd>
    <dt class="col-sm-3">名</dt>
    <dd class="col-sm-9">{{ user.first_name }}</dd>
    <dt class="col-sm-3">メールアドレス</dt>
    <dd class="col-sm-9">{{ user.email }}</dd>
  </dl>
  {% if user.pk == request.user.pk %}
  <a class="btn btn-primary" href="{% url 'kanban:users_update' user.pk  %}" role="button">編集</a>
  {% else %}
  <a class="btn btn-primary disabled" href="#" role="button">編集</a>
  {% endif %}
  {% endblock %}
</div>
{% endblock %}

kanban/templates/kanban/users/update.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>ユーザー編集</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}